// <auto-generated />
using System;
using ControlObraApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlObraApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127030814_AddAvanceFotos")]
    partial class AddAvanceFotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlObraApi.Models.AvanceFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvanceObraId")
                        .HasColumnType("int");

                    b.Property<string>("Orientacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvanceObraId");

                    b.ToTable("AvanceFotos");
                });

            modelBuilder.Entity("ControlObraApi.Models.AvanceObra", b =>
                {
                    b.Property<int>("AvanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvanceID"));

                    b.Property<int>("CostoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoEjecutado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentajeCompletado")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AvanceID");

                    b.HasIndex("CostoID");

                    b.ToTable("AvancesObra");

                    b.HasData(
                        new
                        {
                            AvanceID = 1,
                            CostoID = 1,
                            FechaRegistro = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoEjecutado = 75000.00m,
                            PorcentajeCompletado = 50.00m
                        },
                        new
                        {
                            AvanceID = 2,
                            CostoID = 2,
                            FechaRegistro = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoEjecutado = 10000.00m,
                            PorcentajeCompletado = 22.22m
                        },
                        new
                        {
                            AvanceID = 3,
                            CostoID = 3,
                            FechaRegistro = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MontoEjecutado = 30000.00m,
                            PorcentajeCompletado = 37.50m
                        });
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.Property<int>("CostoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostoID"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MontoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CostoID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("EstimacionesCosto");

                    b.HasData(
                        new
                        {
                            CostoID = 1,
                            Concepto = "Cimentación y Estructura",
                            MontoEstimado = 150000.00m,
                            ProyectoID = 1
                        },
                        new
                        {
                            CostoID = 2,
                            Concepto = "Instalaciones Eléctricas",
                            MontoEstimado = 45000.00m,
                            ProyectoID = 1
                        },
                        new
                        {
                            CostoID = 3,
                            Concepto = "Acabados Interiores",
                            MontoEstimado = 80000.00m,
                            ProyectoID = 2
                        });
                });

            modelBuilder.Entity("ControlObraApi.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoID"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProyectoID");

                    b.HasIndex("UserId");

                    b.ToTable("Proyectos");

                    b.HasData(
                        new
                        {
                            ProyectoID = 1,
                            FechaInicio = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreObra = "Torre Residencial Alpha",
                            Ubicacion = "Zona Central",
                            UserId = 1
                        },
                        new
                        {
                            ProyectoID = 2,
                            FechaInicio = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreObra = "Edificio Comercial Beta",
                            Ubicacion = "Zona Norte",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("ControlObraApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "demo@test.com",
                            Name = "Usuario Demo",
                            PasswordHash = "$2a$11$vY8y8HZg5LqW3z9X2wK7P.7TqK9Z3yN4WqR8P.XmF5Kx9V7Qz8z9e",
                            Role = "User",
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("ControlObraApi.Models.AvanceFoto", b =>
                {
                    b.HasOne("ControlObraApi.Models.AvanceObra", "AvanceObra")
                        .WithMany("Fotos")
                        .HasForeignKey("AvanceObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvanceObra");
                });

            modelBuilder.Entity("ControlObraApi.Models.AvanceObra", b =>
                {
                    b.HasOne("ControlObraApi.Models.EstimacionCosto", "EstimacionCosto")
                        .WithMany("Avances")
                        .HasForeignKey("CostoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstimacionCosto");
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.HasOne("ControlObraApi.Models.Proyecto", "Proyecto")
                        .WithMany("Estimaciones")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ControlObraApi.Models.Proyecto", b =>
                {
                    b.HasOne("ControlObraApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ControlObraApi.Models.AvanceObra", b =>
                {
                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.Navigation("Avances");
                });

            modelBuilder.Entity("ControlObraApi.Models.Proyecto", b =>
                {
                    b.Navigation("Estimaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
