// <auto-generated />
using System;
using ControlObraApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlObraApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251117231705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlObraApi.Models.AvanceObra", b =>
                {
                    b.Property<int>("AvanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvanceID"));

                    b.Property<int>("CostoID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoEjecutado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PorcentajeCompletado")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("AvanceID");

                    b.HasIndex("CostoID");

                    b.ToTable("AvancesObra");
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.Property<int>("CostoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostoID"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoEstimado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("CostoID");

                    b.HasIndex("ProyectoID");

                    b.ToTable("EstimacionesCosto");
                });

            modelBuilder.Entity("ControlObraApi.Models.Proyecto", b =>
                {
                    b.Property<int>("ProyectoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProyectoID"));

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreObra")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProyectoID");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("ControlObraApi.Models.AvanceObra", b =>
                {
                    b.HasOne("ControlObraApi.Models.EstimacionCosto", "EstimacionCosto")
                        .WithMany("Avances")
                        .HasForeignKey("CostoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstimacionCosto");
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.HasOne("ControlObraApi.Models.Proyecto", "Proyecto")
                        .WithMany("Estimaciones")
                        .HasForeignKey("ProyectoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("ControlObraApi.Models.EstimacionCosto", b =>
                {
                    b.Navigation("Avances");
                });

            modelBuilder.Entity("ControlObraApi.Models.Proyecto", b =>
                {
                    b.Navigation("Estimaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
